### ISSUE TITLE
Showing names instead of emails in skills list

### ISSUE THREAD

**Issue by francesco-strazzullo** [claranet-it/it-portfolio-manager-frontend#2]
On the skill list page, we show the emails instead of names. Given that the SSO gives us the name of the user I think that it would be more "friendly" to show names in the list.

@nicolacorvo @gioboa any thoughts?

**Comment by gioboa** [comment]
That information is something managed from the server so if we change the logic there, the frontend will works fine.

**Comment by francesco-strazzullo** [comment]
@nicolacorvo does the backed save this information?

**Comment by nicolacorvo** [comment]
@francesco-strazzullo we don't have this information saved in the DB but we can add a new column in skill-matrix table and return to the FE.
