### ISSUE TITLE
Add Link to this repo for issues

### ISSUE THREAD

**Issue by francesco-strazzullo** [claranet-it/it-portfolio-manager-frontend#25]
We may add a link to this repo to let people know that this is where we collect issues.

**Comment by gioboa** [comment]
<img width="377" alt="Screenshot 2024-01-23 at 09 35 18" src="https://github.com/claranet-it/it-portfolio-manager-frontend/assets/35845425/f904adae-4c4b-49ed-b057-e116aa4a73cd">

<img width="436" alt="Screenshot 2024-01-23 at 09 37 17" src="https://github.com/claranet-it/it-portfolio-manager-frontend/assets/35845425/9fb7f2de-528d-4517-b308-100c6f25e454">

Something like this is enough I guess
