### ISSUE TITLE
Crew name not shown in effort matrix

### ISSUE THREAD

**Issue by mariateresagraziano** [claranet-it/it-portfolio-manager-frontend#28]
Although I have associated my crew, it is not shown in the effort matrix.

![Screenshot 2024-01-24 alle 10 38 00](https://github.com/claranet-it/it-portfolio-manager-frontend/assets/120010049/2cfdc3f9-6bfc-4e3b-86cc-dab6852ac3dd)

**Comment by alefiori** [comment]
Closed in https://github.com/claranet-it/it-portfolio-manager-frontend/pull/16
