### ISSUE TITLE
Show Crew name on people and filter by Crew

### ISSUE THREAD

**Issue by francesco-strazzullo** [claranet-it/it-portfolio-manager-frontend#7]
In the effort page we should be able to show crew name for every person and also filter by crew.

**Comment by alefiori** [comment]
@francesco-strazzullo at the moment we don't have the crew info in the `effort` API. Maybe it could be useful to add it as already implemented in the `skill-matrix` API. /cc @nicolacorvo

**Comment by francesco-strazzullo** [comment]
Or for now you can merge both API on the client, just to test easily the UI part, after that we may ask @nicolacorvo to fix the BE? What do you think?

**Comment by alefiori** [comment]
Yep, it works for me. I'm gonna implement it using the crew info form the `skill-matrix` API
